DAWebPhone/Models/Device.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAWebPhone.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;

    public partial class Device
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Device()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            DvStatus = 0;
        }

        public string Code { get; set; }
        public Nullable<int> ProID { get; set; }
        public string Color { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ImportDate { get; set; }
        public Nullable<int> DvStatus { get; set; }
        public string Note { get; set; }

        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        [NotMapped]
        public string ProName
        {
            get
            {
                DBWebPhoneEntities db = new DBWebPhoneEntities();
                var pro = db.Products.FirstOrDefault(a => a.ProID == ProID);
                return pro.ProName;
            }
        }
    }
}

DAWebPhone/Controllers/DeviceController.cs
using DAWebPhone.App_Start;
using DAWebPhone.Models;
using Microsoft.Ajax.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DAWebPhone.Controllers
{
    public class DeviceController : Controller
    {
        DBWebPhoneEntities db = new DBWebPhoneEntities();
        // GET: Device
        public ActionResult Import()
        {
            if (SessionConfig.GetAdm() == null)
                return RedirectToAction("Login", "Admin");
            var dv = new Device();
            return View(dv);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Import(Device dv)
        {
            if (ModelState.IsValid)
            {
                dv.ImportDate = DateTime.Now;
                db.Devices.Add(dv);
                db.SaveChanges();
            }
            return RedirectToAction("DeviList");
        }
        public ActionResult Search(FormCollection form)
        {
            if (form["ProID"]==null)
                return RedirectToAction("DeviList");
            int id = int.Parse(form["ProID"]);
            return RedirectToAction("DeviceList", new {id = id});
        }
        public ActionResult Edit(string code)
        {
            if (SessionConfig.GetAdm() == null)
                return RedirectToAction("Login", "Admin");
            var dv = db.Devices.FirstOrDefault(a=>a.Code == code);
            if (dv != null)
            {
                return View(dv);
            }
            return RedirectToAction("DeviceList");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Device dv)
        {
            if (ModelState.IsValid)
            {
                var dev = db.Devices.FirstOrDefault(a=>a.Code==dv.Code);
                if(dev != null)
                {
                    dev.ProID = dv.ProID;
                    dev.DvStatus = dv.DvStatus;
                    dev.CreatedDate = dv.CreatedDate;
                    dev.ImportDate = dv.ImportDate;
                    dev.Note = dv.Note;
                    db.SaveChanges();
                    return RedirectToAction("DeviceList");
                }
            }
            ModelState.AddModelError("", "Thông tin không hợp lệ");
            return View();
        }
        public ActionResult Delete(string code)
        {
            if (SessionConfig.GetAdm() == null)
                return RedirectToAction("Login", "Admin");
            var dv = db.Devices.FirstOrDefault(a => a.Code == code);
            if (dv != null)
            {
                return View(dv);
            }
            return RedirectToAction("DeviceList");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Device dv)
        {
            var dev = db.Devices.FirstOrDefault(a=>a.Code==dv.Code);
            db.Devices.Remove(dv);
            db.SaveChanges();
            return RedirectToAction("DeviceList");
        }
        public ActionResult DeviceList(int? id)
        {
            if (SessionConfig.GetAdm() == null)
                return RedirectToAction("Login", "Admin");
            var vms = new List<DeviceDetailViewModel>();
            var ds = db.Devices.ToList();
            if(id!=null)
                ds = db.Devices.Where(a=>a.ProID==id).ToList();
            foreach (var i in ds)
            {
                var vm = new DeviceDetailViewModel();
                vm.Device = i;
                vms.Add(vm);
            }
            return View(vms);
        }
    }
}

DAWebPhone/Views/Device/Delete.cshtml
@model DAWebPhone.Models.Device

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h3 style="text-align:center;color:red;">Xác nhận xóa?</h3>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.ProID)
    <div class="form-actions no-color d-flex justify-content-center">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        @Html.ActionLink("Quay lại", "Index", "", new { @class = "btn btn-success" })
    </div>
}
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Color)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Color)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImportDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImportDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DvStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DvStatus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Note)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Note)
        </dd>

    </dl>

</div>

DAWebPhone/Views/Device/DeviceList.cshtml
@model IEnumerable<DAWebPhone.Models.DeviceDetailViewModel>

@{
    ViewBag.Title = "DeviceList";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<style>
    #s {
        margin: 10px;
        display: inline;
    }
</style>
<div id="s">
    @using (Html.BeginForm("Search", "Device"))
    {
        <a class="btn btn-success" href="@Url.Action("Import","Device")">Thêm mới </a><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
        <input type="number" value="Mã sản phẩm" name="ProID" placeholder="Mã sản phẩm" />
        <input type="submit" value="Tìm" class="btn btn-info" />
    }
</div>


<table class="table table-hover table-bordered">
    <tr>
        <th>Tên sản phẩm</th>
        <th>Mã sản phẩm</th>
        <th>Mã thiết bị</th>
        <th>Màu</th>
        <th>Trạng thái</th>
        <th colspan="2">Ghi chú</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Product.ProName</td>
            <td>@item.Product.ProID</td>
            <td>@item.Device.Code</td>
            <td>@item.Color</td>
            <td>@item.Status</td>
            <td>@item.Device.Note</td>
            <td>
                <a class="btn btn-info" href="@Url.Action("Edit", "Device", new {code = item.Device.Code})">Sửa</a>
                <a class="btn btn-danger" href="@Url.Action("Delete", "Device", new {code = item.Device.Code})">Xóa</a>
            </td>
        </tr>
    }

</table>

DAWebPhone/Views/Device/Edit.cshtml
@model DAWebPhone.Models.Device

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<link href="~/Content/infopages.css" rel="stylesheet" />
<div class="div-tit">
    <h2>Cập nhật thông tin thiết bị</h2>
</div>


        <div class="div-form col-auto">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    @Html.HiddenFor(model => model.Code)
                    @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })

                    <div class="form-group">
                        @Html.LabelFor(model => model.ProID, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.ProID, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ProID, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Color, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Color, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Color, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.CreatedDate, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.CreatedDate, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                            @Html.ValidationMessageFor(model => model.CreatedDate, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.ImportDate, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.ImportDate, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                            @Html.ValidationMessageFor(model => model.ImportDate, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.DvStatus, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.DvStatus, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.DvStatus, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Note, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Note, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Save" class="btn btn-default" />
                        </div>
                    </div>
                </div>
            }
        </div>

DAWebPhone/Views/Device/Import.cshtml
@model DAWebPhone.Models.Device

@{
    ViewBag.Title = "Import";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2 style="text-align:center;color:red;">Nhập hàng</h2>

<div style="padding:40px;padding-left:100px;">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                <label>Mã thiết bị</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label>Mã sản phẩm</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ProID, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ProID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label>Màu sắc</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Color, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Color, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label>Ngày sản xuất</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CreatedDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CreatedDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-10">
                    @Html.HiddenFor(model => model.DvStatus, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>

            <div class="form-group">
                <label>Ghi chú</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Note, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <br />
                    <input type="submit" value="Create" class="btn btn-success" />
                </div>
            </div>
        </div>
    }
</div>